[package]
edition = "2021"
name = "ngrok-js"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
bytes = "1.3.0"
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.10.14", default-features = false, features = ["napi4", "tokio_rt"] }
napi-derive = "2.10.1"
ngrok = { version = "0.8.0" }
tokio = { version = "1.23.0", features = ["sync"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
